// <auto-generated />
using System;
using Aeries_Student_WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aeries_Student_WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aeries_Student_WebApi.Models.Domain.Medical", b =>
                {
                    b.Property<string>("BillingCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalBC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalBU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalBillC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalCO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalET")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalRecordId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalSD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medicalST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("studentID")
                        .HasColumnType("int");

                    b.ToTable("MedicalData");
                });
#pragma warning restore 612, 618
        }
    }
}
